ArizaTakipMVC/ArizaTakipMVC/Controllers/DepartmanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ArizaTakipMVC.Models;

namespace ArizaTakipMVC.Controllers
{
    public class DepartmanController : Controller
    {
        // GET: Departman
        DB_ArizaTakipEntities db = new DB_ArizaTakipEntities(); 


        //Admin sayfasında departmanları listelemeyi sağlar.
        public ActionResult DepartmanListesi()
        {
            //Eğer kullanıcı oturum açmadıysa login ekranına yönlendirilir.
            if (Session["Admin"] == null)
            {
                return RedirectToAction("Login", "Kullanici");
            }

            var departman = db.tbl_Departman.ToList(); //Departmanlar listesini çekiyoruz.
            return View(departman);
        }

        //Admin sayfasında yeni departman eklemeyi sağlar.
        [HttpGet]
        public ActionResult DepartmanEkle()
        {
            //Eğer kullanıcı oturum açmadıysa login ekranına yönlendirilir.
            if (Session["Admin"] == null)
            {
                return RedirectToAction("Login", "Kullanici");
            }
            return View();
        }

        [HttpPost]
        public ActionResult DepartmanEkle(tbl_Departman d)
        {
            //Eğer kullanıcı oturum açmadıysa login ekranına yönlendirilir.
            if (Session["Admin"] == null)
            {
                return RedirectToAction("Login", "Kullanici");
            }
            try
            {
                db.tbl_Departman.Add(d);   //Yeni departman ekliyoruz ve database'e kaydediyoruz.
                db.SaveChanges();
                return RedirectToAction("DepartmanListesi"); //Ekleme işleminden sonra Departmanlar Listesine yönlendiriyoruz.
            }
            catch (Exception)
            {
                throw;
            }
        }

        //Admin sayfasında seçilen departmanı güncellemeyi sağlar.
        [HttpGet]
        public ActionResult DepartmanGuncelle(int id)
        {            
            //Eğer kullanıcı oturum açmadıysa login ekranına yönlendirilir.
            if (Session["Admin"] == null)
            {
                return RedirectToAction("Login", "Kullanici");
            }
            tbl_Departman departman = db.tbl_Departman.Where(t => t.id_Departman == id).SingleOrDefault(); //Güncellenecek olan departmanı id'ye göre çekiyoruz.
            return View(departman);
        }

        [HttpPost]
        public ActionResult DepartmanGuncelle(tbl_Departman d)
        {
            //Eğer kullanıcı oturum açmadıysa login ekranına yönlendirilir.
            if (Session["Admin"] == null)
            {
                return RedirectToAction("Login", "Kullanici");
            }
            try
            {
                tbl_Departman departman = db.tbl_Departman.Where(t => t.id_Departman == d.id_Departman).SingleOrDefault();  //Güncellenecek olan departmanı id'ye göre çekiyoruz.
                departman.DepartmanAd = d.DepartmanAd;  //Departman adını güncelliyoruz.
                db.SaveChanges();
                return RedirectToAction("DepartmanListesi"); //Güncelleme işleminden sonra Departmanlar Listesine yönlendiriyoruz.
            }
            catch (Exception)
            {
                throw;
            }
        }

        //Admin sayfasında seçilen departmanı silmeyi sağlar.
        public ActionResult DepartmanSil(int id)
        {
            //Eğer kullanıcı oturum açmadıysa login ekranına yönlendirilir.
            if (Session["Admin"] == null)
            {
                return RedirectToAction("Login", "Kullanici");
            }

            try
            {
                tbl_Departman departman = db.tbl_Departman.Where(t => t.id_Departman == id).SingleOrDefault(); //Silinecek olan departmanı id'ye göre çekiyoruz.
                db.tbl_Departman.Remove(departman);  //Departmanı siliyoruz.
                db.SaveChanges();

                return RedirectToAction("DepartmanListesi");  //Silme işleminden sonra Departmanlar Listesine yönlendiriyoruz.
            }
            catch (Exception)
            {
                throw;
            }
        }

    }
}

ArizaTakipMVC/ArizaTakipMVC/Views/Departman/DepartmanEkle.cshtml
@using ArizaTakipMVC.Models
@model tbl_Departman

@{
    ViewBag.Title = "DepartmanEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("DepartmanEkle", "Departman", FormMethod.Post))
{
    <h2><i class="fas fa-plus"></i> Yeni Departman Ekle</h2>
    <table class="table table-hover table-bordered">


        <tr>
            <td><label for="inputDepartmanAdi">Departman Adı</label></td>
            <td>@Html.TextBoxFor(model => model.DepartmanAd, new { @class = "form-control", required = "required", placeholder = "Departman adı giriniz" }) </td>
        </tr>
        <tr>
            <td>
                @Html.ActionLink("Departman Listesine Geri dön", "DepartmanListesi")
            </td>
            <td>
                <input type="submit" class="btn btn-success" value="Departman Ekle" />
            </td>
        </tr>
    </table>
}

ArizaTakipMVC/ArizaTakipMVC/Views/Departman/DepartmanGuncelle.cshtml
@using ArizaTakipMVC.Models
@model  tbl_Departman

@{
    ViewBag.Title = "DepartmanGuncelle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm("DepartmanGuncelle", "Departman", FormMethod.Post))
{
    <h2><i class="fas fa-pencil-alt"></i> Departman Güncelle</h2>
    <table class="table table-hover table-bordered">
        @Html.HiddenFor(model => model.id_Departman)

        <tr>
            <td><label for="inputDepartmanAd">Departman Adı</label></td>
            <td>@Html.TextBoxFor(model => model.DepartmanAd, new { @class = "form-control", required = "required", placeholder = "Departman adı giriniz" }) </td>
        </tr>
        <tr>
            <td>
                @Html.ActionLink("Departman Listesine Geri dön", "DepartmanListesi")
            </td>
            <td>
                <input type="submit" class="btn btn-success" value="Departman Adını Güncelle" />
            </td>
        </tr>
    </table>
}

ArizaTakipMVC/ArizaTakipMVC/Views/Departman/DepartmanListesi.cshtml
@using ArizaTakipMVC.Models
@model IEnumerable<tbl_Departman>

@{
    ViewBag.Title = "DepartmanListesi";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2><i class="fas fa-list"></i> Departman Listesi</h2>

<table class="table table-hover table-bordered">
    <tr>
        <th>Departman Adı</th>
        <th>İşlemler</th>
    </tr>
    
    @foreach(tbl_Departman item in Model)
    {
        <tr>

            <td>@Html.DisplayFor(t => item.DepartmanAd)</td>

            <td>
                <a href="~/Departman/DepartmanGuncelle/@item.id_Departman" class="btn btn-success"><i class="fas fa-pencil-alt"></i> Departman Adını Güncelle</a>
                <a href="~/Departman/DepartmanSil/@item.id_Departman" class="btn btn-danger"><i class="fas fa-times"></i> Departman Adını Sil</a>
            </td>
        </tr>
    }
</table>