ArizaTakipMVC/ArizaTakipMVC/Models/ViewModel/ArizaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ArizaTakipMVC.Models.ViewModel
{
    public class ArizaViewModel
    {  
        public tbl_Ariza ArizaYeniKayit { get; set; }
        public List<tbl_Ariza> Arizalar { get; set; }
        public List<tbl_ArizaTur> ArizaTurleri { get; set; }
        public IEnumerable<SelectListItem> ArizaTurListesi { get; set; }

    }
}

ArizaTakipMVC/ArizaTakipMVC/Controllers/ArizaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ArizaTakipMVC.Models;
using ArizaTakipMVC.Models.ViewModel;

namespace ArizaTakipMVC.Controllers
{
    public class ArizaController : Controller
    {
        // GET: Ariza
        DB_ArizaTakipEntities db = new DB_ArizaTakipEntities();


        //Arızaların listelenmesini sağlar.
        public ActionResult ArizaListesi()
        {
            //Eğer kullanıcı oturum açmadıysa login ekranına yönlendirilir.
            if (Session["Kullanici"] == null)
            {
                return RedirectToAction("Login", "Kullanici");
            }

            ArizaViewModel avm = new ArizaViewModel();
            List<SelectListItem> ArizaTurListesi = new List<SelectListItem>();

            // Arıza türlerini SelectListItem ile liste şeklinde alıp dropdownlist'e ekliyoruz.
            foreach (tbl_ArizaTur item in db.tbl_ArizaTur.ToList())
            {
                ArizaTurListesi.Add(new SelectListItem { Value = item.id_ArizaTur.ToString(), Text = item.ArizaTurAd });
            }

            //Oturum açmış kullanıcın id'si
            int id = Convert.ToInt32(User.Identity.Name);

            //Oturum açmış kullanıcı objesi oluşturulur. 
            var myKullanici = db.tbl_Kullanici.FirstOrDefault(k => k.id_Kullanici == id);

            //Kullanıcının türünü yetkilendirme vermek için ViewDatada tutulur. 
            ViewData["id_KullaniciTur"] = myKullanici.id_KullaniciTur;

            //Yalnızca oturum açmış kullanıcının bağlı olduğu departmana ait arızalar listelenir.
            avm.Arizalar = db.tbl_Ariza.Where(t => t.tbl_Kullanici.id_Departman == myKullanici.id_Departman).ToList();
           
            //Arıza türleri listesini çekiyoruz.
            avm.ArizaTurleri = db.tbl_ArizaTur.ToList();
            avm.ArizaTurListesi = ArizaTurListesi;
            avm.ArizaYeniKayit = null;
            return View(avm);
        }

        //Yeni arıza kaydı oluşturulur.
        [HttpPost]
        public ActionResult ArizaKayit(ArizaViewModel a)
        {
            try
            {
                a.ArizaYeniKayit.ArizaGirisTarihi = DateTime.Now;       //Arıza giriş tarihi olarak mevcut oluşturulma tarihi tutulur.
                a.ArizaYeniKayit.id_ArizaDurumTur = 1;                 //Standart olarak beklemede durumu girilir.
                a.ArizaYeniKayit.id_Kullanici = Convert.ToInt32(User.Identity.Name);  //Arızayı oluşturan mevcut kullanıcın id'si.

                db.tbl_Ariza.Add(a.ArizaYeniKayit);  
                db.SaveChanges();

                return RedirectToAction("ArizaListesi"); //Ekleme işleminden sonra Arıza Listesine yönlendiriyoruz.
            }
            catch (Exception)
            {
                throw;
            }
        }

        //Arızayı güncelleme işlemini sağlar.
        [HttpGet]
        public ActionResult ArizaGuncelle(int id)
        {
            //Eğer kullanıcı oturum açmadıysa login ekranına yönlendirilir.
            if (Session["Kullanici"] == null)
            {
                return RedirectToAction("Login", "Kullanici");
            }

            ArizaViewModel avm = new ArizaViewModel(); 
            List<SelectListItem> ArızaTurListesi = new List<SelectListItem>();  //Arıza türleri için tanımlanan SelectListItem

            // Arıza türlerini SelectListItem ile liste şeklinde alıp dropdownlist'e ekliyoruz.
            foreach (tbl_ArizaTur item in db.tbl_ArizaTur.ToList())
            {
                ArızaTurListesi.Add(new SelectListItem { Value = item.id_ArizaTur.ToString(), Text = item.ArizaTurAd });
            }

            avm.ArizaTurListesi = ArızaTurListesi;

             //Güncellenecek olan arızayı id ye göre alıyoruz.
            avm.ArizaYeniKayit = db.tbl_Ariza.Where(t => t.id_Ariza == id).SingleOrDefault();

            return View(avm);
        }

        [HttpPost]
        public ActionResult ArizaGuncelle(ArizaViewModel a)
        {
            try
            {
                tbl_Ariza ariza = db.tbl_Ariza.FirstOrDefault(t => t.id_Ariza == a.ArizaYeniKayit.id_Ariza); //Güncellenecek olan arızayı id'ye göre çekiyoruz.
                ariza.Aciklama = a.ArizaYeniKayit.Aciklama;        //Açıklama güncellenir.
                ariza.id_ArizaTur = a.ArizaYeniKayit.id_ArizaTur;  //Arıza türü güncellenir.
                db.SaveChanges();
                return RedirectToAction("ArizaListesi");          //Güncelleme işleminden sonra Arıza Listesine yönlendiriyoruz.
            }
            catch (Exception)
            {
                throw;
            }
        }

        //Arıza durumunu güncelleme işlemi. (Beklemede,işleme alındı,arıza giderildi,arıza giderilemedi vs.)
        public ActionResult ArizaDurumGuncelle(int id, byte id2)
        {
            //Eğer kullanıcı oturum açmadıysa login ekranına yönlendirilir.
            if (Session["Kullanici"] == null)
            {
                return RedirectToAction("Login", "Kullanici");
            }

            try
            {
                tbl_Ariza ariza = db.tbl_Ariza.FirstOrDefault(t => t.id_Ariza == id); //Güncellenecek olan arıza id ye göre alınır.
                ariza.id_ArizaDurumTur = id2;                                        // Arıza durum id'si

                db.SaveChanges();

                return RedirectToAction("ArizaListesi");  //Güncelleme işleminden sonra Arıza Listesine yönlendiriyoruz.
            }
            catch (Exception)
            {
                throw;
            }
        }

        //Seçili olan arızayı silmeyi sağlar.
        public ActionResult ArizaSil(int id)
        {
            //Eğer kullanıcı oturum açmadıysa login ekranına yönlendirilir.
            if (Session["Kullanici"] == null)
            {
                return RedirectToAction("Login", "Kullanici");
            }

            try
            {
                tbl_Ariza ariza = db.tbl_Ariza.Where(t => t.id_Ariza == id).SingleOrDefault(); //Silinecek olan arızayı id'ye göre alıyoruz.
                db.tbl_Ariza.Remove(ariza);   //Arızayı siliyoruz.
                db.SaveChanges();

                return RedirectToAction("ArizaListesi");     //Silme işleminden sonra Arıza Listesine yönlendiriyoruz.
            }
            catch (Exception)
            {
                throw;
            }
        }

        //Admin sayfasında arıza türlerinin listelenmesini sağlar.
        public ActionResult ArizaTurListesi()
        {
            //Eğer kullanıcı oturum açmadıysa login ekranına yönlendirilir.
            if (Session["Admin"] == null)
            {
                return RedirectToAction("Login", "Kullanici");
            }

            var arizaTur = db.tbl_ArizaTur.ToList();    //Arıza türleri listesini çekiyoruz.
            return View(arizaTur);
        }


        //Admin sayfasında yeni arıza türü eklemeyi sağlar.
        [HttpGet]
        public ActionResult ArizaTurEkle()
        {
            //Eğer kullanıcı oturum açmadıysa login ekranına yönlendirilir.
            if (Session["Admin"] == null)
            {
                return RedirectToAction("Login", "Kullanici");
            }

            return View();
        }

        [HttpPost]
        public ActionResult ArizaTurEkle(tbl_ArizaTur a)
        {
            //Eğer kullanıcı oturum açmadıysa login ekranına yönlendirilir.
            if (Session["Admin"] == null)
            {
                return RedirectToAction("Login", "Kullanici");
            }
            try
            {
                db.tbl_ArizaTur.Add(a);  //Yeni arıza türü eklenir ve db'ye kaydedilir.
                db.SaveChanges();
                return RedirectToAction("ArizaTurListesi"); //Ekleme işleminden sonra Arıza Türleri Listesine yönlendiriyoruz.
            }
            catch (Exception)
            {
                throw;
            }
        }


        //Admin sayfasında seçili olan arıza türünü güncellemeyi sağlar.
        [HttpGet]
        public ActionResult ArizaTurGuncelle(int id)
        {
            //Eğer kullanıcı oturum açmadıysa login ekranına yönlendirilir.
            if (Session["Admin"] == null)
            {
                return RedirectToAction("Login", "Kullanici");
            }
            tbl_ArizaTur arizaTur = db.tbl_ArizaTur.Where(t => t.id_ArizaTur == id).SingleOrDefault(); //Güncellenecek olan arıza türünü id'ye göre alıyoruz.
            return View(arizaTur);
        }

        [HttpPost]
        public ActionResult ArizaTurGuncelle(tbl_ArizaTur a)
        {
            //Eğer kullanıcı oturum açmadıysa login ekranına yönlendirilir.
            if (Session["Admin"] == null)
            {
                return RedirectToAction("Login", "Kullanici");
            }
            try
            {
                tbl_ArizaTur arizaTur = db.tbl_ArizaTur.Where(t => t.id_ArizaTur == a.id_ArizaTur).SingleOrDefault(); //Güncellenecek olan arıza türünü id'ye göre alıyoruz.
                arizaTur.ArizaTurAd = a.ArizaTurAd;   //Arıza tür adı güncellenir.
                db.SaveChanges();
                return RedirectToAction("ArizaTurListesi");  //Güncelleme işleminden sonra Arıza Türleri Listesine yönlendiriyoruz.
            }
            catch (Exception)
            {
                throw;
            }
        }

        //Admin sayfasında seçili olan arıza türünü silmeyi sağlar.
        public ActionResult ArizaTurSil(int id)
        {
            //Eğer kullanıcı oturum açmadıysa login ekranına yönlendirilir.
            if (Session["Admin"] == null)
            {
                return RedirectToAction("Login","Kullanici");
            }

            try
            {
                tbl_ArizaTur arizaTur = db.tbl_ArizaTur.Where(t => t.id_ArizaTur == id).SingleOrDefault(); //Arıza türünü id'ye göre alıyoruz.
                db.tbl_ArizaTur.Remove(arizaTur);  // id'ye göre alınan arıza türünü siliyoruz.
                db.SaveChanges();

ArizaTakipMVC/ArizaTakipMVC/Views/Ariza/ArizaGuncelle.cshtml
@using ArizaTakipMVC.Models
@model ArizaTakipMVC.Models.ViewModel.ArizaViewModel

@{
    ViewBag.Title = "ArizaGuncelle";
    Layout = "~/Views/Shared/_KullaniciLayout.cshtml";
}

@using (Html.BeginForm("ArizaGuncelle", "Ariza", FormMethod.Post))
{
    <h2> <i class="fas fa-pencil-alt"></i> Arıza Kaydını Güncelle</h2>
    <table class="table table-hover table-bordered">
        @Html.HiddenFor(model => model.ArizaYeniKayit.id_Ariza)

        <tr>
            <td><label>Arıza Türü</label></td>
            <td> @Html.DropDownListFor(model => model.ArizaYeniKayit.id_ArizaTur, Model.ArizaTurListesi , new { @class = "form-control" })</td>
        </tr>
        <tr>
            <td><label for="inputArizaAciklama">Açıklama</label></td>
            <td>@Html.TextBoxFor(model => model.ArizaYeniKayit.Aciklama, new { @class = "form-control", required = "required", placeholder = "Açıklama giriniz" }) </td>
        </tr>
        <tr>
            <td>
                @Html.ActionLink("Arıza Listesine Geri dön", "ArizaListesi")
            </td>
            <td>
                <input type="submit" class="btn btn-success" value="Arıza Güncelle" />
            </td>
        </tr>
    </table>
}

ArizaTakipMVC/ArizaTakipMVC/Views/Ariza/ArizaListesi.cshtml
@using ArizaTakipMVC.Models
@model ArizaTakipMVC.Models.ViewModel.ArizaViewModel

@{
    ViewBag.Title = "ArizaListesi";
    Layout = "~/Views/Shared/_KullaniciLayout.cshtml";
}

<link href="~/Content/css/arizaListesi.css" rel="stylesheet" />

<div>
    <button class="btn btn-primary" data-toggle="modal" data-target="#arizaInsertModal"><i class="fas fa-plus"></i> Arıza Kaydı Oluştur</button>
</div>
<br />
<div>
    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th scope="col">Departman</th>
                <th scope="col">Arıza Tür</th>
                <th scope="col">Kaydı Oluşturan Kullanıcı</th>
                <th scope="col">Açıklama</th>
                <th scope="col">Kayıt Tarihi</th>
                <th scope="col">Durum</th>
                <th scope="col">İşlemler</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var ariza in Model.Arizalar)
            {
                <tr>
                    <td>@ariza.tbl_Kullanici.tbl_Departman.DepartmanAd</td>
                    <td>@ariza.tbl_ArizaTur.ArizaTurAd</td>
                    <td>@ariza.tbl_Kullanici.Ad  @ariza.tbl_Kullanici.Soyad</td>
                    <td>@ariza.Aciklama</td>
                    <td>@ariza.ArizaGirisTarihi.ToString("dd/MM/yyyy")</td>
                    <td class="durum_@ariza.tbl_ArizaDurumTur.id_ArizaDurumTur">@ariza.tbl_ArizaDurumTur.ArizaDurumTurAd</td>
                    <td style="white-space: nowrap">


                        @* Arızayı Düzeltme ve Silme yetkileri sadece arızayı oluşturan kullanıcıdadır. *@

                        @if (ariza.id_Kullanici == Convert.ToInt32(User.Identity.Name))
                        {
                            <a href="~/Ariza/ArizaGuncelle/@ariza.id_Ariza" class="btn btn-success"><i class="fas fa-wrench"></i> Düzelt</a>
                            <a href="~/Ariza/ArizaSil/@ariza.id_Ariza" class="btn btn-danger"><i class="fas fa-times"></i> Sil</a>

                        }

                        @* Yalnızca teknik personel statüsündeki kullanıcılar arıza durum türü üzerinde işlem yapmaya yetkilidir. *@

                        @if (ViewData["id_KullaniciTur"].ToString() == "4")
                        {
                            <div class="btn-group" role="group" aria-label="Button group with nested dropdown">


                                <div class="btn-group" role="group">
                                    <button id="btnGroupDrop1" type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fas fa-pencil-alt"></i> Durum Türü Değiştir
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">

                                        <a class="dropdown-item" href="~/Ariza/ArizaDurumGuncelle/@ariza.id_Ariza/1">Beklemede</a>
                                        <a class="dropdown-item" href="~/Ariza/ArizaDurumGuncelle/@ariza.id_Ariza/2">İşleme Alındı</a>
                                        <a class="dropdown-item" href="~/Ariza/ArizaDurumGuncelle/@ariza.id_Ariza/3">Arıza Giderildi</a>
                                        <a class="dropdown-item" href="~/Ariza/ArizaDurumGuncelle/@ariza.id_Ariza/4">Arıza Giderilemedi</a>
                                        <a class="dropdown-item" href="~/Ariza/ArizaDurumGuncelle/@ariza.id_Ariza/5">Dış Servise Gönderildi</a>

                                    </div>
                                </div>
                            </div>
                        }
                    </td>
                </tr>
            }

        </tbody>
    </table>
</div>

<div>
    @* Yeni arıza kaydı eklemek için kullanılan modal. *@

    @using (Html.BeginForm("ArizaKayit", "Ariza", FormMethod.Post))
    {
        <div class="modal fade" id="arizaInsertModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Yeni Arıza Kaydı</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form>
                            <div class="form-group">
                                <label for="message-text" class="col-form-label">Arıza Türü:</label>
                                @Html.DropDownListFor(model => model.ArizaYeniKayit.id_ArizaTur, Model.ArizaTurListesi, new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                <label for="recipient-name" class="col-form-label">Açıklama:</label>
                                @Html.TextBoxFor(model => model.ArizaYeniKayit.Aciklama, new { @class = "form-control", required = "required", placeholder = "Arıza açıklaması giriniz." })
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fas fa-times"></i> Kapat</button>
                        <button type="submit" class="btn btn-primary"><i class="fas fa-plus"></i> Kaydet</button>
                    </div>
                </div>
            </div>
        </div>
    }

</div>

ArizaTakipMVC/ArizaTakipMVC/Views/Ariza/ArizaTurEkle.cshtml
@using ArizaTakipMVC.Models
@model tbl_ArizaTur

@{
    ViewBag.Title = "ArizaTurEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("ArizaTurEkle", "Ariza", FormMethod.Post))
{
    <h2><i class="fas fa-plus"></i> Yeni Arıza Türü Ekle</h2>
    <table class="table table-hover table-bordered">

     
        <tr>
            <td><label for="inputArizaAciklama">Şifre</label></td>
            <td>@Html.TextBoxFor(model => model.ArizaTurAd, new { @class = "form-control", required = "required", placeholder = "Arıza türü adı giriniz" }) </td>
        </tr>
        <tr>
            <td>
                @Html.ActionLink("Arızala Türleri Listesine Geri dön", "ArizaTurListesi")
            </td>
            <td>
                <input type="submit" class="btn btn-success" value="Arıza Türü Ekle" />
            </td>
        </tr>
    </table>
}

ArizaTakipMVC/ArizaTakipMVC/Views/Ariza/ArizaTurGuncelle.cshtml
@using ArizaTakipMVC.Models
@model  tbl_ArizaTur

@{
    ViewBag.Title = "ArizaTurGuncelle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm("ArizaTurGuncelle", "Ariza", FormMethod.Post))
{
    <h2><i class="fas fa-pencil-alt"></i> Arıza Türünü Güncelle</h2>
    <table class="table table-hover table-bordered">
        @Html.HiddenFor(model => model.id_ArizaTur)
     
        <tr>
            <td><label for="inputArizaTurAd">Arıza Türü Adı</label></td>
            <td>@Html.TextBoxFor(model => model.ArizaTurAd, new { @class = "form-control", required = "required", placeholder = "Arıza tür adı giriniz" }) </td>
        </tr>
        <tr>
            <td>
                @Html.ActionLink("Arıza Türleri Listesine Geri dön", "ArizaTurListesi")
            </td>
            <td>
                <input type="submit" class="btn btn-success" value="Arıza Tür Adını Güncelle" />
            </td>
        </tr>
    </table>
}

ArizaTakipMVC/ArizaTakipMVC/Views/Ariza/ArizaTurListesi.cshtml
@using ArizaTakipMVC.Models
@model IEnumerable<tbl_ArizaTur>

@{
    ViewBag.Title = "ArizaTurListesi";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2><i class="fas fa-list"></i> Arıza Türleri Listesi</h2>

<table class="table table-hover table-bordered">
    <tr>
        <th>Arıza Türü</th> 
        <th>İşlemler</th>
    </tr>
    @foreach (tbl_ArizaTur item in Model)
    {
        <tr>
           
            <td>@Html.DisplayFor(t => item.ArizaTurAd)</td>

            <td>
                <a href="~/Ariza/ArizaTurGuncelle/@item.id_ArizaTur" class="btn btn-success"><i class="fas fa-pencil-alt"></i> Arıza Tür Adını Güncelle</a>
                <a href="~/Ariza/ArizaTurSil/@item.id_ArizaTur" class="btn btn-danger"><i class="fas fa-times"></i> Arıza Tür Adını Sil</a>
            </td>
        </tr>
    }
</table>